### ISSUE TITLE
myhub

### ISSUE THREAD

**Issue by jpadilla** [blimpllc/built-with-ember#109]
https://www.myhubapp.com/

Perhaps @ehubbell can help

**Comment by jpadilla** [comment]
<img width="1000" alt="https---www myhubapp com- 20160305" src="https://cloud.githubusercontent.com/assets/83319/13548361/b17f4956-e2c4-11e5-80f4-0ae5b9bbf2f2.png">

<img width="1000" alt="myhub wp condo deposit 20160305" src="https://cloud.githubusercontent.com/assets/83319/13548362/b182bbfe-e2c4-11e5-91a7-68a77730417d.png">

**Comment by ehubbell** [comment]
Hey @jpadilla - Thanks for reaching out. here's a minimized screenshot of the hp. Lemme know if you need anything further.

Cheers,
Eric

![myhub-hp-screenshot](https://cloud.githubusercontent.com/assets/4422450/13591839/b8410fae-e4a9-11e5-81f2-5d9573809554.png)
