### ISSUE TITLE
Zoocasa.com Ember.js submission

### ISSUE THREAD

**Issue by kurtelliott** [blimpllc/built-with-ember#131]
![zoocasa-screenshot](https://cloud.githubusercontent.com/assets/6797148/19809166/1977fb48-9cf6-11e6-8f1d-dc875a20dbf3.png)

[https://www.zoocasa.com/](url)

**Comment by egjiri** [comment]
Our pull request to add Zoocasa was just merged. You can close this Issue. Thanks
