### ISSUE TITLE
Linkedin.com is now built with emberjs

### ISSUE THREAD

**Issue by crsrusl** [blimpllc/built-with-ember#136]
![linkedin](https://cloud.githubusercontent.com/assets/1391215/22248880/96307804-e238-11e6-9578-81860390799a.png)

**Comment by gcollazo** [comment]
@crsrusl that's cool. Feel free to submit a PR [here's how](https://github.com/GetBlimp/built-with-ember/blob/gh-pages/CONTRIBUTING.md) .

**Comment by crsrusl** [comment]
Cool - I've done a pull request https://github.com/GetBlimp/built-with-ember/pull/137
