### ISSUE TITLE
Ally

### ISSUE THREAD

**Issue by jpadilla** [blimpllc/built-with-ember#144]
https://secure.ally.com uses Ember.

**Comment by jpadilla** [comment]
Hey @crodriguez1a, we'd love to have a submission for Ally. Any way you could help us out with a screenshot?

**Comment by crodriguez1a** [comment]
@jpadilla Absolutely man! We'll get one out to you.

Cc/ @alexdiliberto @jbailey4

**Comment by crodriguez1a** [comment]
@jpadilla This obviously is all mock data (btw)
[
![ally-dashboard-screenshot 1](https://cloud.githubusercontent.com/assets/3610417/26835272/f0a2f6f6-4aa5-11e7-864c-30a9f04ed765.png)
](https://secure.ally.com)

**Comment by jpadilla** [comment]
@crodriguez1a thank you, #146 adds this.
