### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by RobbieTheWagner** [blimpllc/built-with-ember#153]
Would be awesome to get some of these sites added. Ember needs as much exposure as it can get 😄

**Comment by gcollazo** [comment]
Hi @rwwagner90 I do what I can but lately finding time has been an issue.

Also the idea of the site is to be a curated list of only ambitious apps (no hobby/weekend projects) so, some PRs need to be closed with a "thanks but we'll pass for now" which makes it even harder to deal with.

Help is always welcome.

**Comment by RobbieTheWagner** [comment]
@gcollazo I could potentially help out. There are lots of legit sites listed in the issues and PRs. There are a few we can close for sure.

**Comment by gcollazo** [comment]
Added you as a contributor. Let me know how can I help. I'm on the ember slack almost every day we can chat there also.

**Comment by jpadilla** [comment]
Thinking back on this, I think I'm OK with accepting most pull requests. We have a **featured** feature that we can use to highlight and curate our favorite picks. Thoughts?

**Comment by RobbieTheWagner** [comment]
@jpadilla I feel like it should still be a somewhat substantial app, not just a throw away project.

**Comment by gcollazo** [comment]
Yes. Apps should not be weekend or throw away hacks
