### ISSUE TITLE
 M.C. Kersten BV 

### ISSUE THREAD

**Issue by broerse** [blimpllc/built-with-ember#16]
http://www.kerstenconstructie.com/

WordPress Backed Ember site.

![kerstenconstructie](https://cloud.githubusercontent.com/assets/1432898/3718025/2e3bc73e-1630-11e4-9928-94d0cf606d83.png)

**Comment by gcollazo** [comment]
Thanks, but we'll pass for now <3.

**Comment by broerse** [comment]
Don't know why. The site is all Ember but it is fine with me.
