### ISSUE TITLE
apple music does not use ember

### ISSUE THREAD

**Issue by ghost** [blimpllc/built-with-ember#164]
<img width="880" alt="screen shot 2019-01-09 at 11 53 33" src="https://user-images.githubusercontent.com/472721/50914733-3a7a5b00-1405-11e9-8a8d-82fd25e7cfc7.png">
They do not appear to use ember so I think that should be removed from teh banner.

**Comment by frabaghe** [comment]
>apple music does not use ember

This is patently false. The example, above, is an Apple.com marketing page—not the Apple Music app.

Anyone can tell that Apple Music is using ember by running Charles Proxy on the requests and looking at the app.js URL and observing all of the ember references.

**Comment by ghost** [comment]
@frabaghe thank you for pointing that out. Perhaps the usage of ember should be qualified. For casual observers this is not obvious.
