### ISSUE TITLE
501thingstodo.com - Let's Explore The World..

### ISSUE THREAD

**Issue by sunnyluthra** [blimpllc/built-with-ember#32]
501thingstodo.com - Handpicked Places, Handpicked Destinations :)
Built with ember
http://501thingstodo.com/  

![screenshot from 2014-08-25 22 02 27](https://cloud.githubusercontent.com/assets/2151462/4032943/81a5dba2-2c75-11e4-9f6f-6a8610ad8a25.png)

**Comment by gcollazo** [comment]
Site doesn't seem to be working. Thanks, but we'll pass for now <3.

**Comment by sunnyluthra** [comment]
Yes i was toying with my mySql server, anyways site is up now but i think it does not deserve to be the part of built with ember. I will try to make some thing cool and will post again.
