### ISSUE TITLE
Add Science Exchange Collaboration Page!

### ISSUE THREAD

**Issue by rosschapman** [blimpllc/built-with-ember#47]
```

---
layout: post
title: "Science Exchange Collaboration Page"
slug: science-exchange
source: https://www.scienceexchange.com/

---

<img src="/screenshots/science-exchange.png">
```

![science-exchange](https://cloud.githubusercontent.com/assets/5185/5655799/d1f353ec-9687-11e4-8315-3f0d5a6b92f2.png)

**Comment by rosschapman** [comment]
@gcollazo did you get a chance to check us out?  I think we are a pretty unique use case.  Thx!

**Comment by jpadilla** [comment]
@rosschapman this looks good to me but would you mind creating a Pull Request with the post and image?
