### ISSUE TITLE
By Request Only?

### ISSUE THREAD

**Issue by trek** [blimpllc/built-with-ember#5]
Or can we push sites up: https://docs.google.com/document/d/1ZWYq3gwkPTzUiyqr4x_asSj8wIgfvg8XyLmU3Yx_FPE/edit has a ton of great stuff on it.

**Comment by jpadilla** [comment]
@trek we should update the **Submissions** section of the About page to reflect this better. If it's built with Ember it should go in. So no, not by request only. We'd definitely prefer people fork and add more posts. The only thing we'd like to require are the screenshots for each post.

**Comment by gcollazo** [comment]
@supabok make sure you fork the repo and push your changes there fist. I can't find your fork.

**Comment by supabok** [comment]
@gcollazo Just did! thank you for this ;)

**Comment by rogeruiz** [comment]
@jpadilla Can _anyone_ fork this to add more posts or do we need to be affiliated with the company? Is it just the idea that projects need more screenshots? This is a task I could take; to go through that list and crop some screenshots.

**Comment by jpadilla** [comment]
@rogeruiz Yea, anyone can definitely fork this and send a Pull Request back, we'll make sure everything looks good and just merge it. We definitely could use help going through that list and creating posts.

**Comment by gcollazo** [comment]
@jpadilla I agree. Maybe we should do tags or categories on entries? Right now we only have a long list of posts and we need a way to surface the "best ones" or "editor's picks".

What do you think?

**Comment by trek** [comment]
:+1: on making this list curated. I think that [equivalent site for angular](https://builtwith.angularjs.org/) is ridiculous. It's mostly personal weekend project/demo sites instead of real world products. I don't think that site does a great job of demoing what Angular can do.

**Comment by rogeruiz** [comment]
Word up on making it curated. How do you start going about that? I agree with @trek that personal / weekend / demo projects shouldn't supersede real world products. The idea of demoing what Ember can do is great. Maybe we shoot for categorizations of Ember apps?

**Comment by gcollazo** [comment]
I think we need to set a list of minimum requirements. After the requirements are met an "editor" should decide if the site goes in or not.

**Goals**
- Keep the site content as high quality as possible.
- Make decision process as transparent as possible.
- Be kind and helpful to submitters of rejected sites.

**Minimum Requirements**
- No personal / weekend or demo projects
- Real world products or applications
- If you submit a _content websites_ like (Bustle or NBC News) it should be a "certain size???". No blogs or company websites

What you think? Any other ideas? @trek @rogeruiz @jpadilla

**Comment by trek** [comment]
seems good to have some minimum guidelines although I'm 100% certain people will ignore them and submit anyway.

@mdo does a nice job just saying _no_: https://github.com/twbs/bootstrap-expo/issues/1087, https://github.com/twbs/bootstrap-expo/issues/1097, etc.

It's perfectly acceptable to just use your judgement here and only take the best of the best.

**Comment by gcollazo** [comment]
@trek thanks for the advise. We'll go with that for now.
