### ISSUE TITLE
http://app.sush.io

### ISSUE THREAD

**Issue by julienXX** [blimpllc/built-with-ember#52]
[Sush.io](http://sush.io) is a tool for all your Stripe financial tasks needs.

![sushio](https://cloud.githubusercontent.com/assets/53949/6231881/ad808fa0-b6c8-11e4-8947-4a5aebc91ef7.png)

**Comment by jpadilla** [comment]
@julienXX thanks!

**Comment by julienXX** [comment]
@jpadilla thank you :)
