### ISSUE TITLE
Add a "Famous projects" section

### ISSUE THREAD

**Issue by jkneb** [blimpllc/built-with-ember#72]
I believe it would good for the whole Ember community to add some kind of a "all of fame" section on the site.

Like for instance: 
Apple Music, Heroku, Intercom, Square, Nest Store, Twitch, NBC, Travis, Vine and Apple Help all deserve to be in that category. 

This way people can see with their own eyes that Ember is actually used for real for big projects.

**Comment by gcollazo** [comment]
Thanks for suggesting it @jkneb. I like the idea of a new page showing the "Hall of fame". While we are at it maybe also add a little carousel on the home page showing a random selection of a few of the featured apps. Here's my idea.

![sketch](https://cloud.githubusercontent.com/assets/61048/8546201/ae5dd03a-2483-11e5-97b3-3b16a18329aa.png)

**Comment by jkneb** [comment]
Yeah this way those "famous" projects can be visible directly from the home page. 

Like the idea.

:)

**Comment by jkneb** [comment]
Hey, had some spare time... did this.

![featured](https://cloud.githubusercontent.com/assets/805719/11845848/17e39c12-a416-11e5-9e6c-8384946a2e97.gif)

**Comment by gcollazo** [comment]
@jkneb I like the idea of having a lot of sites there like you propose. I think we should look into using some sort of slider widget that provides other means of navigation other than horizontal scrolling which is not that good on Windows. Also have in mind that this should work on mobile devices.

I really like what Apple does on its website.

![screencast 2015-12-16 12-08-46](https://cloud.githubusercontent.com/assets/61048/11846204/f00ae61e-a3ed-11e5-92ee-5d81e7b74b00.gif)

**Comment by jkneb** [comment]
Windows... what's this?

**Comment by jkneb** [comment]
Alright, I'll need jQuery to achieve this kind of effect. Probably nothing more actually.

**Comment by gcollazo** [comment]
That sounds good. We can use jQuery right from a CDN.

**Comment by jkneb** [comment]
So, I've implemented a basic solution with some good old jQuery code, very procedural but very effective. It's responsive and apparently ie9+ 
The best part is that it's based on the browser's native scroll, which means it works also on mobile devices with touch events :smiling_imp: 

What do you think, good for a first PR?

![scroll-slider](https://cloud.githubusercontent.com/assets/805719/11875726/5f63e5bc-a4e6-11e5-8cd6-67a48c3649ff.gif)

**Comment by gcollazo** [comment]
Looks good.
